version: "3.7"
services:
  postgresql:
    image: postgres:10
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/PostgreSQL/data:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: "6677446633"
    networks:
      db:
        aliases:
          - postgresql
  
  adminer:
    image: adminer:4
    container_name: adminer
    restart: always
    ports:
      - "8088:8080"
    networks:
      db:
        aliases:
          - adminer

networks:
  db:
    name: db
