version: "3.7"
services:
  frps:
    image: snowdreamtech/frps:0.43.0
    container_name: frps
    ports:
      - "7000:7000"
      - "7070:7070"
      - "80:80"
      - "443:443"
      - "8000-8030:8000-8030"
    volumes:
      - ../conf/frps.ini:/etc/frp/frps.ini
    restart: always
    networks:
      reverse-proxy:
        aliases:
          - frps

networks:
  reverse-proxy:
    name: reverse-proxy
    