version: "3.7"
services:
  django:
    image: django-3.2.13
    container_name: my-django-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../app:/usr/src/app:rw
    working_dir: /usr/src/app
    # 添加tty配置，阻断系统自动重启的进程
    tty: true
    restart: always
    